___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Pandas Series

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

### **Using Lists**

In [4]:
pd.Series(labels)


0    a
1    b
2    c
dtype: object

In [5]:
pd.Series()

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series([10,20,30,40])

0    10
1    20
2    30
3    40
dtype: int64

### **Using NumPy Arrays**

In [8]:
arr

array([10, 20, 30])

In [9]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int64

### **Using Dictionary**

In [10]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(d, index=["a","w","e"]) # sadece eşleşen keys ler görüntülenir diğerleri nan döner.

a    10.0
w     NaN
e     NaN
dtype: float64

In [16]:
pd.Series(data="Sami", index=range(1,5))

1    Sami
2    Sami
3    Sami
4    Sami
dtype: object

### Using Scalar Value

In [17]:
pd.Series(data="Sami", index=range(1,5))

1    Sami
2    Sami
3    Sami
4    Sami
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [21]:
set1 = (1,2,3,4,5)

In [22]:
pd.Series(set1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [26]:
pd.Series([set, list, dict])[0]([2,3,4,5,6,7,8,9])

{2, 3, 4, 5, 6, 7, 8, 9}

In [27]:
pd.Series([set, list, dict])[1]([2,3,4,5,6,7,8,9])

[2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
pd.Series([sum, print,len])[0]([3,4,5])

12

In [35]:
mix_data = ['Aziz', 2, True]
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [36]:
type(ser)

pandas.core.series.Series

In [39]:
ser.dtype

dtype('O')

In [43]:
type(ser[2])

bool

In [42]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [44]:
type(arr[0])

numpy.str_

In [45]:
type(arr[2])

numpy.str_

### Basic Attributes of Series

In [2]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    26
1    64
2     2
3    78
4    27
5    67
6    49
dtype: int32

In [6]:
ser.dtype

dtype('int32')

In [7]:
ser.shape

(7,)

In [8]:
ser.size

7

In [9]:
len(ser)

7

In [10]:
ser.ndim

1

In [11]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [12]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [13]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [14]:
ser

0    49
1    28
2    15
3    45
4    13
5     6
6    45
dtype: int32

In [18]:
ser.keys

<bound method Series.keys of 0    49
1    28
2    15
3    45
4    13
5     6
6    45
dtype: int32>

In [20]:
ser.values

array([49, 28, 15, 45, 13,  6, 45])

In [21]:
for i in ser.values:
    print(i)

49
28
15
45
13
6
45


In [31]:
ser.item

<bound method IndexOpsMixin.item of 0    49
1    28
2    15
3    45
4    13
5     6
6    45
dtype: int32>

In [6]:
ser.item

<bound method IndexOpsMixin.item of 0    83
1    87
2    75
3    57
4    73
5    40
6    13
dtype: int32>

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [7]:
ser.tail()

2    75
3    57
4    73
5    40
6    13
dtype: int32

In [8]:
ser.sample(3)

6    13
5    40
4    73
dtype: int32

In [9]:
ser.sort_index()

0    83
1    87
2    75
3    57
4    73
5    40
6    13
dtype: int32

In [5]:
ser.isin([83])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [8]:
a =pd.Series([i for i in "clarusway"])
a

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [10]:
a.isin(["l","s"])

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
dtype: bool

In [11]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [13]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [15]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [18]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [19]:
ser2.sort_values

<bound method Series.sort_values of USA        1
Germany    2
Italy      5
Japan      4
dtype: int64>

In [20]:
ser1[1]

2

In [22]:
ser1["Germany"]

2

In [23]:
ser1.Germany # tavsiye edilmiyor, index str ve boşluksuz ise yazılabilir.

2

Operations are then also done based off of index:

In [24]:
ser1 + ser2 # iki serdede olan index değerlerine ait valueler toplanır(eşleşen)

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

### pandas_series[index] | pandas_series[[indices, indices...]]

In [25]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [26]:
ser3[0]

'a'

In [27]:
ser3[:2]

0    a
1    b
dtype: object

In [28]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

In [29]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [31]:
panser[["terry","orion"]] # ayrı ayrı çağıracağımızda 2 kmşeliparentez

terry    121
orion    150
dtype: int64

In [32]:
panser["terry":"orion"]

terry      121
micheal    200
orion      150
dtype: int64

In [33]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [34]:
panser


terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [35]:
panser.keys

<bound method Series.keys of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [36]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [37]:
for index, value in panser.items():
    print(index,value)

terry 121
micheal 200
orion 150
jason 99


In [38]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [43]:
panser.item

<bound method IndexOpsMixin.item of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [44]:
panser.items()

In [47]:
for index, value in panser.items():
    print(index,value)

terry
micheal
orion
jason


In [53]:
"terry" in panser.index

True

In [52]:
200 in panser.values

True

In [54]:
panser.isin([200,160])

terry      False
micheal     True
orion      False
jason      False
dtype: bool

In [57]:
panser["terry"] = 190

In [58]:
panser

terry      190
micheal    200
orion      150
jason       99
dtype: int64

In [59]:
panser[panser > 100]

terry      190
micheal    200
orion      150
dtype: int64

In [60]:
panser[panser > 100] = 175

In [61]:
panser

terry      175
micheal    175
orion      175
jason       99
dtype: int64